### ISSUE TITLE
[BUG] Encountering bug when installing the service using the simple install script (Ubuntu 20.04)

### ISSUE THREAD

**Issue by creyD** [frappe/bench#1091]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?

**Describe the bug** :chart_with_downwards_trend:
The easy install script fails with the following error:

```subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.```

**To Reproduce** :page_with_curl:
Do exactly the steps described here https://github.com/frappe/bench#easy-install-script on a brand new machine with ubuntu:20.04.1

**Expected behavior** :chart_with_upwards_trend:
When running the install script it should install the program with no problems.

**OS (please complete the following information):** :cyclone:
- [ x] Linux: `ubuntu:20.04.1`
**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch:5.2.1

**Comment by creyD** [comment]
I tested it on a new machine using ubuntu 18 and it worked flawlessly.

**Comment by markelayan** [comment]
Same issue here, Ubuntu 16.4 fresh installation, tried 3 times.

**Comment by markelayan** [comment]
fixed in my case:

local settings were not set and pip did not work without it, set locals in the following commands and it worked:
```export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales```

**Comment by creyD** [comment]
I did the export command too, but for me it didn't fix the problem. Thanks for providing the full error log!

**Comment by gavindsouza** [comment]
I generally add the env variables in `/etc/environment` and restart my session. Works for me.

**Comment by weasam** [comment]
My fresh Ubuntu 18
same bug came up, I guess this bug is from ansible, no have host file under /etc/ansible, and ansible-playbook doesn't work properly. I tried all the ways ( manually, script, docker) doesn't work, the docker install stuck at error " project_name" doesn't exist, 

Edited 2021/1/30
Installed successful on Ubunto ARM Architecture Raspberry PI, lol
https://www.digitalocean.com/community/tutorials/how-to-install-an-erpnext-stack-on-ubuntu-20-04#step-6-%E2%80%94-installing-frappe-bench-cli

**Comment by weasam** [comment]
> I did the export command too, but for me it didn't fix the problem. Thanks for providing the full error log!

Have you fix it now to install？ I've try to install since 3 days ago

**Comment by creyD** [comment]
As I mentioned earlier, I installed it on ubuntu 18 and it worked, so I didn't try it anymore. @weasam

**Comment by mr-engin3er** [comment]
is anyone have solution? i also got same error.


`Traceback (most recent call last):
  File "install.py", line 472, in <module>
    install_bench(args)
  File "install.py", line 264, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 388, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.`

**Comment by markelayan** [comment]
> is anyone have solution? i also got same error.
> 
> 
> 
> 
> 
> `Traceback (most recent call last):
> 
>   File "install.py", line 472, in <module>
> 
>     install_bench(args)
> 
>   File "install.py", line 264, in install_bench
> 
>     run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
> 
>   File "install.py", line 388, in run_playbook
> 
>     success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
> 
>   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
> 
>     raise CalledProcessError(retcode, cmd)
> 
> subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.`


Your issue can be solved with this export:

``` export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales```

**Comment by sealj553** [comment]
This did not fix the error in my case. Same message, Ubuntu 20.04.

**Comment by chucklin72** [comment]
> This did not fix the error in my case. Same message, Ubuntu 20.04.

Same with me. Ubuntu 20.04 fresh install with apt-get update

**Comment by sealj553** [comment]
The steps in this guide worked great for me on Ubuntu 20.04: https://www.digitalocean.com/community/tutorials/how-to-install-an-erpnext-stack-on-ubuntu-20-04#step-6-%E2%80%94-installing-frappe-bench-cli

**Comment by digitalrevisor** [comment]
Same issue in Ubuntu 18.04.

`Traceback (most recent call last):
  File "install.py", line 492, in <module>
    install_bench(args)
  File "install.py", line 278, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 408, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.
`
End of log file doesn't contain any special error
`RUNNING HANDLER [mariadb : restart mysql] ***************************************************************************************************************************************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/mariadb/handlers/main.yml:2

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=38   changed=9    unreachable=0    failed=1    skipped=48   rescued=0    ignored=0

Install script run at 14:52 on 2021-02-22
`
I don't know if its useful but the db log shows three attempted accesses to the database using root but without password during the time the installation script is running.

**Comment by neelbhanushali** [comment]
**$cat /etc/os-release**
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Steps provided [here](https://mariadb.com/kb/en/mariadb-installation-dependancy-problems-and-failed-to-start-service/) solved the problem

**Comment by thesherifr** [comment]
> The steps in this guide worked great for me on Ubuntu 20.04: https://www.digitalocean.com/community/tutorials/how-to-install-an-erpnext-stack-on-ubuntu-20-04#step-6-%E2%80%94-installing-frappe-bench-cli


I recommend very much these guided steps, very informative, easy to copy and I have used them for installing a fresh instance of ERPNext 13.. there was only one step below that did not work with me but I was able to skip it:

sudo bash nodesource_setup.sh

**Comment by weasam** [comment]
> 

Yes, This tutorial is working

**Comment by gavindsouza** [comment]
Closing thread. Open a new issue for newer distros/setups
